server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/disaster_opportunity_engine
spring.datasource.username=root
spring.datasource.password=Koolgee994$$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

news.api.key=34f4c1689a054cff963016832c5e6284
openai.api.key=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